version: '2'

services:
  postgres:
    image: postgres:9.6
  web:
    restart: always
    environment:
      - DJANGO_SECRET_KEY=local
    image: web
    build: ./
    command: >
      bash -c "./timemapper-cms/manage.py migrate &&
               ./timemapper-cms/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  # js:
  #   restart: always
  #   image: web
  #   build: ./
  #   command: >
  #     bash -c "cd ./cms-app/ && yarn start"
  #   volumes:
  #     - ./:/code
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - web
